version: '2'
services:
  green:
    build: ./server/
    command: python /bin/server.py
    ports:
      - "8001:8001"
    volumes:
      - ./server/server.py:/bin/server.py
    environment:
      PORT: 8001
      COLOR: green

  blue:
    build: ./server/
    command: python /bin/server.py
    volumes:
      - ./server/server.py:/bin/server.py
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      COLOR: blue

  proxy:
    build: ./proxy
    command: /bin/run_nginx
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:8080"
      - "8282:8282"
    external_links:
      - bluegreen_blue_1:blue-host
      - bluegreen_green_1:green-host


  bash:
    stdin_open: true
    tty: true
    build: ./proxy/
    command: /bin/bash
    volumes:
      - ./:/app
